[tool.poetry]
name = "trac"
version = "0.1.0"
description = ""
authors = ["Eugene Park <eugenepark3@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
tox = "^4.13.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
